name: Awesome Inc U
description: "Learn to Code"
url: http://www.awesomeincu.com
highlighter: pygments
permalink: /blog/:year/:month/:day/:title/
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
exclude: [node_modules]
collections:
    applications:
        output: true
        permalink: /applications/:path/
    interest:
        output: true
        permalink: /interest/:path/
    notes:
        output: true
        permalink: /notes/:path/
    programs:
        output: true
        permalink: /:path/
    services:
        output: true
        permalink: /services/:path/
    tutorials:
        output: true
        permalink: /tutorials/:path/