---
title: Awesomeincu 2015
timezone: UTC
collections:
  applications:
    title: Applications
    output: true
    permalink: "/applications/:path/"
  courses:
    title: Courses
    output: true
    permalink: "/:path/"
  interest:
    title: Interest
    output: true
    permalink: "/interest/:path/"
  notes:
    title: Notes
    output: true
    permalink: "/notes/:path/"
  posts:
    title: Posts
    output: true
  tutorials:
    title: Tutorials
    output: true
    permalink: "/tutorials/:path/"
  uploads:
    title: Uploads
    output: true
name: Awesome Inc U
url: https://www.awesomeincu.com
description: Learn to Code in Lexington, Kentucky
author: Awesome Inc
google_verification: oiWfM5j5u1IuiWaAkBu8lKyqs5o1ilQCfnM0raw6JPk
highlighter: rouge
permalink: "/blog/:year/:month/:day/:title/"
plugins:
- jekyll-redirect-from
- jekyll-sitemap
exclude:
- node_modules
students-taught: 1400
