name: Awesome Inc U
url: http://www.awesomeincu.com
description: "Learn to Code classes for kids and adults in Lexington, Kentucky."
highlighter: pygments
permalink: /blog/:year/:month/:day/:title/
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
exclude: [node_modules]
collections:
    applications:
        output: true
        permalink: /applications/:path/
    interest:
        output: true
        permalink: /interest/:path/
    notes:
        output: true
        permalink: /notes/:path/
    courses:
        output: true
        permalink: /:path/
    tutorials:
        output: true
        permalink: /tutorials/:path/