name: Awesome Inc U
highlighter: pygments
permalink: /blog/:year/:month/:day/:title/


# Config for Prose.io, an online editor for writing blog posts
prose:
  rooturl: '_posts'
  siteurl: 'http://www.awesomeincu.com/'
  media: 'img/blog/'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "description"
        field:
          element: "text"
          label: "description"
          value: ""
