name: Awesome Inc U
description: "Learn to Code"
highlighter: pygments
permalink: /blog/:year/:month/:day/:title/
gems:
  - jekyll-redirect-from
collections:
    notes:
        output: true
        permalink: /notes/:path/
    programs:
        output: true
        permalink: /programs/:path/
    services:
        output: true
        permalink: /services/:path/
    applications:
        output: true
        permalink: /applications/:path/
    tutorials:
        output: true
        permalink: /tutorials/:path/